# Modified version of Agda's travis.yml

language: haskell

sudo: false

# We build with all the latest GHC versions for each 7.X, so we reduce
# build times, possibly avoid compiler bugs and still test all the major
# interface changes.

ghc:
  - 7.8.4
  - 7.6.3
  - 7.4.2

install:
  # With old GHCs, we get an old cabal-install
  - cabal install -j cabal-install
  - export PATH=$HOME/.cabal/bin:$PATH
  # Showing Cabal configuration
  - cat $HOME/.cabal/config
  # GO GO GO
  - cabal install --enable-tests --only-dependencies -j

script:
  - cabal configure -v2 --enable-tests
  - cabal build -v2
  - travis_wait cabal install -v2 --enable-tests
  - cabal test

matrix:
  fast_finish: false

branches:
  only:
    - master
    - dev
