# Modified version of Agda's travis.yml

language: haskell

# We build with all the latest GHC versions for each 7.X, so we reduce
# build times, possibly avoid compiler bugs and still test all the major
# interface changes.

# Travis have no GHC 7.2.* installed because it is considered a technology
# preview (as per https://www.haskell.org/ghc/download_ghc_7_2_2). If
# necessary, we could use use the approach described in
# https://github.com/hvr/multi-ghc-travis.

ghc:
  - 7.8.4
  - 7.6.3
  - 7.4.2

install:
  # Apparently travis doesn't have "time".
  - sudo apt-get install time
  # With old GHCs, we get an old cabal-install
  - cabal install cabal-install
  - export PATH=$HOME/.cabal/bin:$PATH
  # Showing Cabal configuration
  - cat $HOME/.cabal/config
  # GO GO GO
  - cabal install --enable-tests --only-dependencies -j

script:
  - cabal configure -v2 --enable-tests
  - cabal build -v2
  - travis_wait cabal install -v2 --enable-tests
  - cabal test

# Builds are loooong, we want to send an email as fast as possible.
matrix:
  fast_finish: false

# Every master and maintenance branches >= 2.4.3 or >= maint-2.4.2 must
# be here. You can also add your private branches if you want travis to
# test them.
branches:
  only:
    - master
    - dev
